config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]

  namespace :admin do
    resources :dashboard, only: [:index]
  end

  # Notice that `resource` is singular. Unlike `resources`,
  # `resource` will create routes that are meant to do CRUD
  # on a single thing. There will be no index route or any
  # route with :id. When using singular resource, the controller
  # it links to should still be plural.
  resource :session, only: [:new, :create, :destroy]

  resources :products do
    # creates the following route for us:
    # post('/products/:product_id/reviews', { to: 'reviews#create', as: :product_reviews })
    # Which, due to the `as` creates a method called `product_reviews_path`
    # This method requires one variable, a product or product id to "fill in"
    # the value for `:product_id` in the path
    # It returns the value: '/products/:product_id/reviews' with the :product_id
    # "filled in"
    resources :reviews, shallow: true, only: [:create, :destroy] do
      resources :likes, only: [:create, :destroy]
      resources :votes, only: [:create, :update, :destroy]
    end
    resources :favourites, shallow: true, only: [:create, :destroy]
  end

  resources :favourites, only: [:index]

  patch "/reviews/:id/toggle" => "reviews#toggle_hidden", as: "toggle_hidden"

  resources :news_articles

    # API routes
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :products
      resource :session, only: [:create, :destroy]
    end
  end

  root 'welcome#index'
  get('/about', { to: 'welcome#about', as: :about })
  get('/contact_us', { to: 'contacts#index', as: :contact })
  post('/contact_us', { to: 'contacts#create' })
end

app/models/product.rb
class Product < ApplicationRecord
   belongs_to :user
   has_many :reviews, dependent: :destroy
   has_many :favourites, dependent: :destroy
   has_many :favouriters, through: :favourites, source: :user
   has_many :taggings, dependent: :destroy
   has_many :tags, through: :taggings


  validates(:title, presence: true, uniqueness: true, case_sensitive: false)
  validates(:price, numericality: { greater_than: 0 })
  validates(:description, presence: true, length: { minimum: 10 })
  before_validation :set_default_value_price
  before_save :capitalize_product_title
  # validate: (:set_default_value_price)

  scope(:search, ->(query) { where("title ILIKE ?", "%#{query}%") })

  def tag_names
    self.tags.map{ |t| t.name }.join(",")
  end

  # Appending = at the end of a method name, allows to implement
  # a "setter". A setter is a method that is assignable.
  # Example:
  # p.tag_names = "stuff,yo"
  # The code in the example above would call the method we wrote
  # below where the value on the right-hand side of the = would
  # become the argument to the method.
  # This is similar to implementing an `attr_writer`.
  def tag_names=(rhs)
    self.tags = rhs.strip.split(/\s*,\s*/).map do |tag_name|
      Tag.find_or_initialize_by(name: tag_name)
    end
  end

  private

  def set_default_value_price
    self.price ||= 1
  end

  def capitalize_product_title
    self.title.capitalize!
  end
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < Api::ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize!, only: [:update, :destroy]

  def index
    products = Product.order(created_at: :desc)
    render json: products, each_serializer: ProductCollectionSerializer
  end

  def show
    render json: product
  end

  def create
    product = Product.new product_params
    product.user = current_user
    if product.save
      render json: { id: product.id }
    else
      render(
        json: { errors: product.errors },
        status: 422 # Unprocessable Entity
      )
    end
  end

  def update
    if product.update product_params
      render json: { id: product.id }
    else
      render(
        json: { errors: product.errors },
        status: 422 # Unprocessable Entity
      )
    end
  end

  def destroy
    product.destroy
    render(json: { status: 200 }, status: 200)
  end


  private

  def product_params
    params.require(:product).permit(:title, :description, :price, tag_ids: [])
  end

  def product
    @product ||= Product.find params[:id]
  end

  def authorize!
    render(json: { status: 401 }, status: 401) unless can? :crud, product
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  before_action :authorize!, only: [:edit, :update, :destroy]

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params
    @product.user = current_user
    if @product.save
      ProductMailer.notify_product_owner(@product).deliver_now
      redirect_to @product
      # same as redirect_to product_path(@product)
    else
      # render will simply render the new.html.erb view in the views/products
      # directory. The #new action above will not be touched.
      render :new
    end
  end

  def index
    if params[:tag]
      @tag = Tag.find_or_initialize_by(name: params[:tag])
      @products = @tag.products.order(created_at: :DESC)
    else
      @products = Product.order(created_at: :DESC)
    end
  end

  def show
    @review = Review.new
    # In this case only the product owner will have all reviews available in the
    # through @reviews (including hidden reviews).
    # You could also remove this logic here and do some logic in the view. Your use case (and
    # for now, the size of your Rails toolset) will determine the best way to things.
    # We've done it this way because with the tools available to us it minimizes the
    # amount of repeated code and if else statements in our view.
    if can? :crud, @product
      @reviews = @product.reviews.sort_by { |review| -1 * review.vote_total }
      # We're only using sort_by here because the records are limited to the number of reviews for
      # a specifc product. If we were having to sort thousands of records on every product page
      # this wouldn't be very performant as 'sort_by' will load the entire collection into
      # memory. Here is an ugly SQL statement that works instead:
      # @reviews = @product.reviews.left_outer_joins(:votes).select("reviews.*", "SUM(CASE WHEN votes.is_up = TRUE then 1 ELSE 0 END + CASE WHEN votes.is_up = FALSE then -1 ELSE 0 END) AS votes_count").group("reviews.id").order("votes_count DESC")
      # If we wanted to use a SQL statement we should probably refactor into a method in our Review model,
      # but we may also want to also refactor how we're storing up/down votes in the db.
    else
      @reviews = @product.reviews.where(hidden: false).sort_by { |review| -1 * review.vote_total }
    end
    @favourite = @product.favourites.find_by_user_id current_user if user_signed_in?
  end

  def edit
  end

  def update
    if @product.update product_params
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
   @product.destroy
   redirect_to products_path
  end

  private

  def product_params
    # strong parameters are used primarily as a security practice to help
    # prevent accidentally allowing users to update sensitive model attributes.
    params.require(:product).permit(:title, :description, :price, :tag_names)
  end

  def find_product
    @product = Product.find params[:id]
  end

  def authorize!
    redirect_to root_path, alert: "access denied" unless can? :crud, @product
  end
end

app/views/products/_form.html.erb
<%= form_with model: @product, local: true do |f| %>
  <% if @product.errors.any? %>
  <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>
  <div class="form-group">
    <%= f.label :tag_names %>
    <%= f.text_field :tag_names %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

<script>
  // Documentation for selectize.js:
  // https://selectize.github.io/selectize.js/
  // For description of options that are usable go to:
  // https://github.com/selectize/selectize.js/blob/master/docs/usage.md
  $("#product_tag_names").selectize({
    delimiter: ',',
    persist: false,
    labelField: "name",
    valueField: "name",
    searchField: "name",
    options: <%= Tag.select(:name).to_json(except: [:id]).html_safe %>,
    create (input) {
      return { name: input }
    }
  })
</script>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<h1>Products</h1>

<% if @tag.present? %>
  <h6>
    Showing products tagged by:
    <span class="badge badge-pill badge-primary">
      <%= @tag.name %>
    </span>
  </h6>
<% end %>

 <% @products.each do |product|  %>
  <ul>
    <li><%= link_to product.title, product_path(product) %></li>
  </ul>
<% end %>

app/views/products/new.html.erb
<h1>Add a new product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<h1><%= @product.title %></h1>
<p>Description: <%= @product.description %></p>
<p>Price: <%= number_to_currency(@product.price) %></p>
<p>Sold by: <%= @product.user.full_name %></p>

<% unless @product.tags.empty? %>
  <div>
    <% @product.tags.each do |tag| %>
      <%= link_to(
          tag.name,
          products_path(tag: tag.name), class: "badge badge-pill badge-primary"
      ) %>
    <% end %>
  </div>
<% end %>

<% if can? :edit, @product %>
  <%= link_to "Edit Product", edit_product_path(@product) %> |
<% end %>
<% if can? :destroy, @product %>
  <%= link_to "Delete Product", product_path(@product), method: :delete, data: { confirm: 'Are you sure that you want to delete this product?' } %>
<% end %>

<% if user_signed_in? && can?(:favourite, @product) %>
  <% if @favourite.present? %>
    <%= link_to fa_icon('star'), favourite_path(@favourite), method: :delete, style: 'color: yellow;' %>
  <% else %>
    <%= link_to fa_icon('star-o'), product_favourites_path(@product), method: :post, style: 'color: lightgrey;' %>
  <% end %>
<% end %>
<hr />
<h3>Leave a review</h3>
<%#
  New Review Form
  `form_with model: [@product, @review]` requires there to be a method called
  `product_reviews_path` defined in routes. Using the `resources` method in
  routes, this gets defined for us (see config/routes.rb)
  @review is an empty (non-persisted) review (Review.new) defined in `products#show`
%>
<%= form_with model: [@product, @review], local: true do |f| %>
  <% if @review.errors.present? %>
    <p>
      <%= @review.errors.full_messages.join(', ') %>
    </p>
  <% end %>
  <div>
    <%= f.label :rating %>
    <%= f.number_field :rating, in: 1..5 %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>

<hr />
<h3>Reviews</h3>
<%#
  Display all of the reviews for this product
%>
<% @reviews.each do |review| %>
  <div class="<%= 'hidden-review' if review.hidden %>">
    <h3>Rating: <%= review.rating %></h3>
    <p>
      <%= review.body %>
    </p>
    <p>Reviewed by: <%= review.user.full_name %></p>

    <% if can? :crud, review %>
      <%= link_to 'Delete', review_path(review), method: :delete, data: { confirm: 'Are you sure that you want to delete this review?' } %>
    <% end %>
    <% if can? :crud, @product %>
      <%= link_to "#{review.hidden ? 'Show' : 'Hide' }", toggle_hidden_path(review), method: :patch %>
    <% end %>

    <% if can?(:like, review) %>
      <% like = current_user.likes.find_by_review_id(review) %>
      <% if like %>
        <%= link_to fa_icon('thumbs-up 3x'), like_path(like), method: :delete %>
      <% else %>
        <%= link_to fa_icon('thumbs-o-up 3x'), review_likes_path(review), method: :post %>
      <% end %>
    <% end %>
    (<%= pluralize review.likes.count, 'like' %>) |

  <% vote = review.votes.find_by(user: current_user) %>
  <span class="vote-widget">
    <% if vote.nil? %>
      <%= link_to(fa_icon('arrow-up'), review_votes_path(review, is_up: true), method: :post) %>
      <%= review.vote_total %>
      <%= link_to(fa_icon('arrow-down'), review_votes_path(review, is_up: false), method: :post) %>
    <% elsif vote.is_up? %>
      <%= link_to(fa_icon('arrow-up'), vote_path(vote), method: :delete, class: 'active') %>
      <%= review.vote_total %>
      <%= link_to(fa_icon('arrow-down'), vote_path(vote, is_up: false), method: :patch) %>
    <% else %>
      <%= link_to(fa_icon('arrow-up'), vote_path(vote, is_up: true), method: :patch) %>
      <%= review.vote_total %>
      <%= link_to(fa_icon('arrow-down'), vote_path(vote), method: :delete, class: 'active') %>
    <% end %>
  </span>
  (<%= review.vote_total %>)

  </div>
<% end %>