config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]

  namespace :admin do
    resources :dashboard, only: [:index]
  end

  # Notice that `resource` is singular. Unlike `resources`,
  # `resource` will create routes that are meant to do CRUD
  # on a single thing. There will be no index route or any
  # route with :id. When using singular resource, the controller
  # it links to should still be plural.
  resource :session, only: [:new, :create, :destroy]

  resources :products do
    # creates the following route for us:
    # post('/products/:product_id/reviews', { to: 'reviews#create', as: :product_reviews })
    # Which, due to the `as` creates a method called `product_reviews_path`
    # This method requires one variable, a product or product id to "fill in"
    # the value for `:product_id` in the path
    # It returns the value: '/products/:product_id/reviews' with the :product_id
    # "filled in"
    resources :reviews, shallow: true, only: [:create, :destroy] do
      resources :likes, only: [:create, :destroy]
      resources :votes, only: [:create, :update, :destroy]
    end
    resources :favourites, shallow: true, only: [:create, :destroy]
  end

  resources :favourites, only: [:index]

  patch "/reviews/:id/toggle" => "reviews#toggle_hidden", as: "toggle_hidden"

  resources :news_articles

    # API routes
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :products
      resource :session, only: [:create, :destroy]
    end
  end

  root 'welcome#index'
  get('/about', { to: 'welcome#about', as: :about })
  get('/contact_us', { to: 'contacts#index', as: :contact })
  post('/contact_us', { to: 'contacts#create' })
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmazonSolutionPublicSep18</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container-fluid">
    <nav>
       <%= link_to 'Home', root_path %>
       |
       <%= link_to 'About Us', about_path %>
       |
       <%= link_to 'Contact Us', contact_path %>
       |
       <%= link_to 'New Product', new_product_path %>
       |
       <%= link_to 'All Products', products_path %>
       |
       <% if user_signed_in? %>
        <span>Hello, <%= current_user.first_name %>!</span>
        |
        <%= link_to 'Favourite Products', favourites_path %>
        |
        <%= link_to 'Sign Out', session_path, method: :delete %>
        <% if current_user.admin? %>
         |
         <%= link_to 'Dashboard', admin_dashboard_index_path %>
       <% end %>
      <% else %>
        <%= link_to 'Sign In', new_session_path %>
        |
        <%= link_to 'Sign Up', new_user_path %>
      <% end %>
     </nav>

     <% flash.each do |type, message| %>
        <div class="flash-message alert alert-<%= type %>">
          <%= message %>
        </div>
    <% end %>
    <%= yield %>
  </body>
</html>